baseURL = 'https://codingferpa.org/codingpedia'
languageCode = 'pt-br'
title = 'Codingpedia'
contentDir = 'content'
enableEmoji = true

[module]

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[[menus.primary]]
name = "Documentação"
url = "docs/about/"
weight = 10

[[menus.primary]]
name = "Contribuir"
url = "docs/howto/"
weight = 20

[[menus.primary]]
name = "GitHub"
url = "https://github.com/coding-ferpa/Codingpedia"
weight = 30

[markup]
[markup.tableOfContents]
endLevel = 3
startLevel = 1
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = false

[params]
google_fonts = [["Poppins", "400;500;600;700"], ["JetBrains Mono", "400;500"]]

[params.social]
github = 'coding-ferpa'

[params.footer]
copyright = "© :YEAR: Coding Ferpa. Todos os direitos reservados"
copyrightYearToken = ":YEAR:"

[params.docs]
title = "Codingpedia"
darkMode = true
themeColor = "codingferpa"
logoLinkURL = "docs/about/"
google_fonts = [["Poppins", "400;500;600;700"], ["JetBrains Mono", "400;500"]]
sans_serif_font = "Poppins"
secondary_font = "Poppins"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
